all:
	gcc -fPIC -shared -O2 -D_PG_ORCL_ -DPGXC -DXCP -DXZ -DTBASE -o moonshot.so moonshot.c -I/data/TBase/install/TBase_bin_v2.0/include/postgresql/server -I/data/TornadoVM/etc/dependencies/TornadoVM-jdk21/jdk-21.0.1/include -I/data/TornadoVM/etc/dependencies/TornadoVM-jdk21/jdk-21.0.1/include/linux
